# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2019-04-17 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='introduction',
        ),
    ]
