# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2019-04-04 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bizlog',
            options={'default_permissions': (), 'ordering': ['-id'], 'permissions': (('view_visitor', '\u8bbf\u95ee\u7ec8\u7aef\u7edf\u8ba1'), ('manage_version', '\u7248\u672c\u7ba1\u7406'), ('view_feedback', '\u5efa\u8bae\u53cd\u9988'), ('view_log', '\u7cfb\u7edf\u65e5\u5fd7'), ('manage_vcode', '\u7cfb\u7edf\u9a8c\u8bc1\u7801\u7ba1\u7406')), 'verbose_name': '\u7cfb\u7edf'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'default_permissions': (), 'ordering': ['-id'], 'verbose_name': '\u7528\u6237\u53cd\u9988'},
        ),
        migrations.AlterModelOptions(
            name='vcode',
            options={'default_permissions': (), 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'default_permissions': (), 'ordering': ['-id'], 'verbose_name': '\u7248\u672c\u4fe1\u606f'},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'default_permissions': (), 'ordering': ['-id']},
        ),
    ]
