# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2019-04-10 11:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u652f\u51fa\u5907\u6ce8')),
                ('balance', models.FloatField(verbose_name='\u652f\u51fa\u91d1\u989d')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u652f\u51fa\u65f6\u95f4')),
            ],
            options={
                'default_permissions': (),
                'db_table': 'expense',
                'verbose_name': '\u652f\u51fa\u660e\u7ec6\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Icome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u6536\u5165\u5907\u6ce8')),
                ('balance', models.FloatField(verbose_name='\u6536\u5165\u91d1\u989d')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u6536\u5165\u65f6\u95f4')),
            ],
            options={
                'default_permissions': (),
                'db_table': 'icome',
                'verbose_name': '\u6536\u5165\u660e\u7ec6\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u79d1\u76ee\u540d\u79f0')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, '\u6536\u5165'), (1, '\u652f\u51fa')], verbose_name='\u79d1\u76ee\u7c7b\u522b')),
                ('code', models.CharField(max_length=10, verbose_name='\u79d1\u76ee\u7f16\u7801')),
            ],
            options={
                'default_permissions': (),
                'db_table': 'subject',
                'verbose_name': '\u79d1\u76ee\u7ba1\u7406',
            },
        ),
        migrations.AddField(
            model_name='icome',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergarten.Subject', verbose_name='\u79d1\u76ee'),
        ),
        migrations.AddField(
            model_name='icome',
            name='kindergarten',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='classes.Kindergarten', verbose_name='\u5e7c\u513f\u56ed'),
        ),
        migrations.AddField(
            model_name='icome',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_icome', to=settings.AUTH_USER_MODEL, verbose_name='\u63d0\u4ea4\u4eba'),
        ),
        migrations.AddField(
            model_name='expense',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergarten.Subject', verbose_name='\u79d1\u76ee'),
        ),
        migrations.AddField(
            model_name='expense',
            name='kindergarten',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='classes.Kindergarten', verbose_name='\u5e7c\u513f\u56ed'),
        ),
        migrations.AddField(
            model_name='expense',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_expense', to=settings.AUTH_USER_MODEL, verbose_name='\u652f\u51fa\u4eba'),
        ),
    ]
