# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2019-04-10 11:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='\u5e10\u53f7')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u59d3\u540d')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, '\u7ba1\u7406\u5458'), (1, '\u56ed\u4f01\u8d26\u53f7'), (2, '\u6295\u8d44\u4eba'), (3, '\u56ed\u957f'), (4, '\u6559\u5e08')], default=0, verbose_name='\u7c7b\u522b')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u72b6\u6001')),
                ('time_locked', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='\u9501\u5b9a\u65f6\u95f4')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='\u6ce8\u518c\u65f6\u95f4')),
                ('last_login_ip', models.GenericIPAddressField(editable=False, null=True, verbose_name='\u6700\u540e\u767b\u5f55IP')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'default_permissions': (),
                'permissions': (('manage_investors', '\u6295\u8d44\u4eba'), ('manage_company', '\u56ed\u4f01'), ('manage_kindergardenor', '\u5e7c\u513f\u56ed\u56ed\u957f'), ('manage_teacher', '\u6559\u5e08')),
                'db_table': 'auth_user',
                'verbose_name': '\u8d26\u53f7',
            },
        ),
        migrations.CreateModel(
            name='KindergartenManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kinder_managers', to='classes.Kindergarten', verbose_name='\u6240\u5c5e\u5e7c\u513f\u56ed')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bind_kindergartenor', to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'default_permissions': (),
                'db_table': 'auth_kindergarten_manager',
                'verbose_name': '\u5e7c\u513f\u56ed\u56ed\u957f',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_teacher', to='classes.Classes', verbose_name='\u6240\u5c5e\u73ed\u7ea7')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bind_teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
                'db_table': 'auth_teacher',
                'verbose_name': '\u6559\u5e08\u7ba1\u7406',
            },
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('username', 'type')]),
        ),
    ]
