# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2019-04-10 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u63d0\u4ea4\u5907\u6ce8')),
                ('days', models.IntegerField(blank=True, null=True, verbose_name='\u7f3a\u52e4\u5929\u6570')),
                ('balance', models.FloatField(blank=True, null=True, verbose_name='\u9000\u6b3e\u91d1\u989d')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '\u5f85\u5ba1\u6838'), (1, '\u5b8c\u6210')], default=0, verbose_name='\u72b6\u6001')),
                ('review_notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5ba1\u6838\u5907\u6ce8')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='classes.Student', verbose_name='\u5b66\u751f')),
            ],
            options={
                'default_permissions': (),
                'db_table': 'absence',
                'verbose_name': '\u7f3a\u52e4\u9000\u8d39\u7533\u8bf7',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '\u6b63\u5e38'), (1, '\u7f3a\u52e4')], default=0, verbose_name='\u8003\u52e4')),
                ('start_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u7b7e\u5230\u65f6\u95f4')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5907\u6ce8')),
                ('student', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='classes.Student', verbose_name='\u5b66\u751f')),
            ],
            options={
                'default_permissions': (),
                'db_table': 'attendance',
                'verbose_name': '\u8003\u52e4',
            },
        ),
    ]
