# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2019-04-12 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20190411_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absence',
            old_name='user',
            new_name='student',
        ),
        migrations.AddField(
            model_name='absence',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='\u63d0\u4ea4\u65e5\u671f'),
        ),
    ]
