# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2019-04-13 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20190412_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '\u5f85\u5ba1\u6838'), (1, '\u901a\u8fc7'), (2, '\u62d2\u7edd')], default=0, verbose_name='\u72b6\u6001'),
        ),
    ]
